SW automation
Tino-FRC-2473/FRC2024 pull request #6
Opened 2024-01-25 00:30 UTC by AknA13

2024-01-25 18:22 UTC, tanmayi2 submitted a review, later dismissed
looks good, we should add the apriltag library code next time (maybe separate methods for different libraries)

2024-02-02 00:33 UTC, mirapanigrahy commented on src/main/java/frc/robot/Constants.java
delete this class and directly enter the string for the data table in RasberryPI.java

2024-02-02 00:39 UTC, mirapanigrahy requested changes, later dismissed

2024-02-02 00:39 UTC, mirapanigrahy commented on src/main/java/frc/robot/Constants.java
> +		public static final String TABLE_NAME = "datatable";
delete this class and directly enter the string for the data table in RasberryPI.java

2024-02-02 00:39 UTC, mirapanigrahy commented on src/main/python/cam1_photos/Photoon1-8-24at618PM#2.jpg
are these photos necessary?

2024-02-02 05:27 UTC, AG6GR commented
Please rebase onto main to clear merge conflicts.

2024-02-05 02:05 UTC, mirapanigrahy commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +					VisionConstants.SPEAKER_TAG_ANGLE_DEGREES, null, null, null,
The same values will probably not work for autonomous as for teleop since the odometry/starting direction will be different depending on the path. Will we need to access these during auto?

2024-02-05 02:05 UTC, mirapanigrahy commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +							&& z2 == VisionConstants.UNABLE_TO_SEE_TAG_CONSTANT)) {
Just wondering, did you add the code so that it stops moving when it can't see the tag?

2024-02-05 02:06 UTC, mirapanigrahy approved these changes

2024-02-05 02:20 UTC, tanmayi2 commented on src/main/python/main.py
> +    print('Loop time: ' + str(time.time()-p))
we should probably take out the timing for each loop

2024-02-05 08:04 UTC, AknA13 commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +					VisionConstants.SPEAKER_TAG_ANGLE_DEGREES, null, null, null,
Not for SVR but for MBR we might have to in order to do multiple speaker cycles in auto

2024-02-05 08:05 UTC, AknA13 commented on src/main/java/frc/robot/systems/DriveFSMSystem.java
> +							&& z2 == VisionConstants.UNABLE_TO_SEE_TAG_CONSTANT)) {
I haven't added it yet but I'll add in the next merge

2024-02-05 08:06 UTC, merged